version: '3.8'

services:
  database:
    image: mariadb:${MARIADB_TAG}
    container_name: ${PROJECT_NAME}_db
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - '4306:3306'
    volumes:
      - ./mariadb:/var/lib/mysql
  
  php:
    container_name: ${PROJECT_NAME}_php
    build:
      context: ./php
      dockerfile: Dockerfile
      args:
        PHP_TAG: ${PHP_TAG}
        PROJECT_NAME: ${PROJECT_NAME}
        GIT_USER_NAME: ${GIT_USER_NAME}
        GIT_USER_EMAIL: ${GIT_USER_EMAIL}
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/${PROJECT_NAME}
      - ./php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - database
  
  nginx:
    container_name: ${PROJECT_NAME}_nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/${PROJECT_NAME}
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database